Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.define "agent" do |agent|
    agent.vm.network "private_network", ip: "192.168.32.115"
    agent.vm.hostname = "agent"
    agent.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 4096
    end
    agent.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "provisioning/playbook/agent.yml"
      ansible.install_mode = "default"
    end
  end

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.network "private_network", ip: "192.168.32.113"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
    jenkins.vm.provision "file", source: ".vagrant/machines/agent/virtualbox/private_key", destination: "/home/vagrant/agent_key"
    jenkins.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "provisioning/playbook/master.yml"
      ansible.install_mode = "default"
    end
  end

end
