#*****************************************************************************
#*                                                                           *
#* Copyright FUJITSU LIMITED 2021                                            *                                                                     *
#* Creation Date: 22-04-2021                                                 *
#*                                                                           *
#*****************************************************************************
# Copyright (c) 2020 Darin Pope

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.network "private_network", ip: "192.168.32.113"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider "jenkins" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "agent1" do |agent1|
    agent1.vm.network "private_network", ip: "192.168.32.115"
    agent1.vm.hostname = "agent1"
    agent1.vm.provider "agent1" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end
end