Vagrant.configure('2') do |config|

  config.vm.box = 'azure'

  config.ssh.private_key_path = 'path to your ssh private key which will be used for authenticating to VM'

  config.vm.provider :azure do |azure, override|

    override.vm.synced_folder ".", "/vagrant", disabled: true

    azure.tenant_id = ENV['AZURE_TENANT_ID']
    azure.client_id = ENV['AZURE_CLIENT_ID']
    azure.client_secret = ENV['AZURE_CLIENT_SECRET']
    azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

    azure.resource_group_name = 'oscm-vagrant'
    azure.location = 'westeurope'
    azure.vm_name = 'vagranttest'
    azure.vm_size = 'Standard_B1s'
    azure.vm_image_urn = 'OpenLogic:CentOS:7.5:latest'
  end

  config.vm.provision "file", source: "provisioning/playbook.yml", destination: "/home/vagrant/playbook.yml"
  config.vm.provision "shell", path: "provisioning/script1.sh"

end
