Vagrant.configure('2') do |config|

  config.vm.box = 'azure'

  config.ssh.private_key_path = 'key'

  config.vm.provider :azure do |azure, override|

    override.vm.synced_folder ".", "/vagrant", disabled: true

    azure.tenant_id = ENV['AZURE_TENANT_ID']
    azure.client_id = ENV['AZURE_CLIENT_ID']
    azure.client_secret = ENV['AZURE_CLIENT_SECRET']
    azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

    azure.resource_group_name = 'oscm-vagrant'
    azure.location = 'westeurope'
    azure.vm_name = 'vagranttest'
    azure.vm_size = 'Standard_B1s'
    azure.vm_image_urn = 'Canonical:UbuntuServer:18.04-LTS:latest'
  end

  config.vm.provision "file", source: "provisioning/playbook.yml", destination: "/home/vagrant/playbook.yml"
  config.vm.provision "file", source: "provisioning/jobs/", destination: "/home/vagrant/"
  config.vm.provision "file", source: "provisioning/init.groovy.d/", destination: "/home/vagrant/"
  config.vm.provision "file", source: "provisioning/vaultList.yml", destination: "/home/vagrant/vaultList.yml"
  config.vm.provision "file", source: "provisioning/paths.yml", destination: "/home/vagrant/paths.yml"
  config.vm.provision :shell do |s|
    s.env = {AZURE_TENANT_ID:ENV['AZURE_TENANT_ID'], AZURE_CLIENT_ID:ENV['AZURE_CLIENT_ID'], AZURE_OBJECT_ID:ENV['AZURE_OBJECT_ID'], AZURE_SUBSCRIPTION_ID:ENV['AZURE_SUBSCRIPTION_ID'], AZURE_CLIENT_SECRET:ENV['AZURE_CLIENT_SECRET']}
    s.path = 'provisioning/script1.sh'
  end
  
end
