Vagrant.configure('2') do |config|

  config.vm.box = 'azure'
  
  config.ssh.private_key_path = 'C:\Users\KOWALCZYKA\.ssh\id_rsa'

  config.vm.provider :azure do |azure, override|
    azure.tenant_id = ENV['AZURE_TENANT_ID']
    azure.client_id = ENV['AZURE_CLIENT_ID']
    azure.client_secret = ENV['AZURE_CLIENT_SECRET']
    azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

    azure.resource_group_name = 'oscm-rg'
    azure.location = 'eastus'
    azure.vm_name = 'vagranttest001'
    azure.vm_size = 'Standard_B1s'
    azure.vm_image_urn = 'Canonical:UbuntuServer:18.04-LTS:latest'
  end

end
